In [18]:
import pandas as pd
from urllib.parse import urlparse
import langdetect

# Set it to being deterministic at language detection
langdetect.DetectorFactory.seed = 0

In [19]:
def detect_text_language(text):
    try:
        return langdetect.detect(text)
    except langdetect.lang_detect_exception.LangDetectException:
        return "Unknown"

In [20]:
df = pd.read_csv("all-languages.csv")
df.shape

(69329, 6)

In [21]:
df["tld"] = df["url"].map(lambda u: urlparse(u).hostname.split(".")[-1])

In [22]:
df["language"] = df["text"].map(lambda t: detect_text_language(t))

In [23]:
percents = pd.DataFrame(columns=["tld", "percent", "total"])

for tld in df["tld"].unique():
    total = df.query("tld == @tld").shape[0]
    if total < 50:
        continue

    en_count = df.query("tld == @tld and language == 'en'").shape[0]
    
    percent = en_count/total * 100
    percents.loc[-1] = [tld, percent, total]
    percents.index = percents.index + 1  # shifting index
    percents = percents.sort_index()  # sorting by index

In [27]:
percents.sort_values("percent", ascending=False, ignore_index=True)

       tld     percent  total
0       ke  100.000000     68
1       nz   97.101449    138
2       au   96.740741    675
3       uk   96.657682   1855
4      edu   96.471418   1417
5      gov   95.752896    518
6       us   94.270833    192
7     link   92.156863     51
8      top   91.666667     84
9   online   90.721649     97
10      in   89.838710    620
11      cc   87.209302     86
12      za   87.078652    178
13      id   85.589520    229
14     app   85.542169     83
15      ca   84.345048    313
16    shop   84.000000    100
17      io   77.631579     76
18    info   77.127660    188
19      co   76.515152    132
20     org   71.632587   6162
21      eu   68.877551    196
22      vn   67.512690    197
23      tw   65.822785     79
24      hu   65.517241    203
25      mx   65.116279     86
26      ro   64.539007    141
27      me   63.414634     82
28     com   63.043864  39463
29      tr   60.150376    133
30      rs   59.420290     69
31      gr   57.553957    139
32     xyz   57.232704    159
33      no   55.882353    102
34      ch   53.179191    173
35      es   50.450450    222
36      ar   49.606299    127
37     net   49.368368   3958
38      at   48.648649    148
39      dk   45.679012    162
40      be   45.643154    241
41      br   45.178571    560
42      ir   44.354839    124
43      pl   43.238434    562
44      de   42.263844   1228
45      ua   41.935484    124
46      nl   41.207815    563
47      fr   37.788779    606
48      sk   37.606838    117
49      kz   37.037037     54
50      it   36.672630    559
51      cz   35.240964    332
52      se   35.074627    134
53      ru   33.863275   1258
54      pt   32.743363    113
55      fi   31.428571    105
56      cl   28.571429     91
57      cn   26.574501    651
58      jp   23.270440    795
59      by   11.494253     87

In [29]:
percents.query("percent > 85").sort_values("percent", ascending=False)["tld"].tolist()

['ke',
 'nz',
 'au',
 'uk',
 'edu',
 'gov',
 'us',
 'link',
 'top',
 'online',
 'in',
 'cc',
 'za',
 'id',
 'app']